#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="${ROOT_DIR}/../FFmpeg-master"
BUILD_DIR="${ROOT_DIR}/build"
DEVICE_BUILD_DIR="${BUILD_DIR}/iphoneos/arm64"
SIM_ARM64_BUILD_DIR="${BUILD_DIR}/iphonesimulator/arm64"
SIM_X86_64_BUILD_DIR="${BUILD_DIR}/iphonesimulator/x86_64"
XCFRAMEWORK_DIR="${BUILD_DIR}/CleanFFmpeg.xcframework"
SIM_UNIVERSAL_DIR="${BUILD_DIR}/iphonesimulator/universal"
INCLUDE_DIR="${ROOT_DIR}/include"
SUPPORT_DIR="${ROOT_DIR}/support"
MIN_IOS_VERSION="13.0"
PREFIX_HEADER="${ROOT_DIR}/include/cleanffmpeg_prefix.h"
PREFIX_HEADER_BACKUP="${BUILD_DIR}/cleanffmpeg_prefix.h"

if [ ! -d "${SRC_DIR}" ]; then
  echo "FFmpeg source directory not found: ${SRC_DIR}"
  exit 1
fi

mkdir -p "${BUILD_DIR}" "${SUPPORT_DIR}"

generate_empty_prefix_header() {
  mkdir -p "${ROOT_DIR}/include"
  {
    echo "// Generated by build_clean_ffmpeg.sh."
    echo "// Bootstrap build: no symbol mappings."
    echo "#ifndef CLEANFFMPEG_PREFIX_H"
    echo "#define CLEANFFMPEG_PREFIX_H"
    echo "#endif"
  } > "${PREFIX_HEADER}"
}

generate_prefix_header_from_libraries() {
  local library
  {
    echo "// Generated by build_clean_ffmpeg.sh."
    echo "// Private symbol namespace for the local FFmpeg build."
    echo "#ifndef CLEANFFMPEG_PREFIX_H"
    echo "#define CLEANFFMPEG_PREFIX_H"
    for library in "$@"; do
      nm -gU "${library}"
    done | awk '
      $NF ~ /^_(av|ff|sws|swresample)/ &&
      $NF !~ /^_av_log2(_16bit)?$/ &&
      $(NF - 1) ~ /^[TDBSC]$/ {
        symbol = $NF
        sub(/^_/, "", symbol)
        print "#define " symbol " cleanffmpeg_" symbol
      }
    ' | sort -u
    echo "#endif"
  } > "${PREFIX_HEADER}"
}

generate_empty_prefix_header

cat > "${SUPPORT_DIR}/CleanFFmpegDummy.m" <<'EOF'
#import <Foundation/Foundation.h>
@interface CleanFFmpegDummy : NSObject
@end
@implementation CleanFFmpegDummy
@end
EOF

copy_public_headers() {
  local install_include_dir="$1"
  rm -rf "${INCLUDE_DIR}"
  mkdir -p "${INCLUDE_DIR}"
  rsync -a "${install_include_dir}/" "${INCLUDE_DIR}/"
  cp "${ROOT_DIR}/CleanFFmpeg.h" "${INCLUDE_DIR}/CleanFFmpeg.h"
  cp "${PREFIX_HEADER_BACKUP}" "${INCLUDE_DIR}/cleanffmpeg_prefix.h"
}

build_one() {
  local sdk="$1"
  local arch="$2"
  local use_prefix="$3"
  local out_dir="${BUILD_DIR}/${sdk}/${arch}"
  local prefix="${out_dir}/install"
  local sdk_path
  local cc
  local ar
  local ranlib
  local cflags
  local ldflags

  rm -rf "${out_dir}"
  mkdir -p "${out_dir}"

  sdk_path="$(xcrun --sdk "${sdk}" --show-sdk-path)"
  cc="$(xcrun --sdk "${sdk}" -f clang)"
  ar="$(xcrun --sdk "${sdk}" -f ar)"
  ranlib="$(xcrun --sdk "${sdk}" -f ranlib)"

  if [ "${sdk}" = "iphoneos" ]; then
    cflags="-arch ${arch} -isysroot ${sdk_path} -miphoneos-version-min=${MIN_IOS_VERSION} -fno-stack-protector -fno-strict-aliasing -O2 -fPIC"
    ldflags="-arch ${arch} -isysroot ${sdk_path} -miphoneos-version-min=${MIN_IOS_VERSION}"
  else
    cflags="-arch ${arch} -isysroot ${sdk_path} -mios-simulator-version-min=${MIN_IOS_VERSION} -fno-stack-protector -fno-strict-aliasing -O2 -fPIC"
    ldflags="-arch ${arch} -isysroot ${sdk_path} -mios-simulator-version-min=${MIN_IOS_VERSION}"
  fi
  if [ "${use_prefix}" = "YES" ]; then
    cflags="${cflags} -include ${PREFIX_HEADER}"
  fi

  pushd "${out_dir}" >/dev/null
  "${SRC_DIR}/configure" \
    --prefix="${prefix}" \
    --disable-programs \
    --disable-doc \
    --disable-debug \
    --disable-network \
    --disable-avdevice \
    --disable-swresample \
    --disable-swscale \
    --disable-avfilter \
    --disable-everything \
    --enable-avutil \
    --enable-avcodec \
    --enable-avformat \
    --enable-muxer=mp4 \
    --enable-parser=h264 \
    --enable-parser=aac \
    --enable-bsf=h264_mp4toannexb \
    --enable-bsf=aac_adtstoasc \
    --enable-protocol=file \
    --enable-small \
    --disable-asm \
    --enable-static \
    --disable-shared \
    --enable-cross-compile \
    --target-os=darwin \
    --arch="${arch}" \
    --cc="${cc}" \
    --ar="${ar}" \
    --ranlib="${ranlib}" \
    --extra-cflags="${cflags}" \
    --extra-ldflags="${ldflags}"

  make -j"$(sysctl -n hw.ncpu)"
  make install
  popd >/dev/null
}

# Build a throwaway device slice first. The exported symbols from this exact
# configuration are the only symbols safe to namespace; scanning source code
# also catches static inline helpers such as av_bswap32 and breaks compilation.
build_one iphoneos arm64 NO
generate_prefix_header_from_libraries \
  "${DEVICE_BUILD_DIR}/install/lib/libavutil.a" \
  "${DEVICE_BUILD_DIR}/install/lib/libavcodec.a" \
  "${DEVICE_BUILD_DIR}/install/lib/libavformat.a"
cp "${PREFIX_HEADER}" "${PREFIX_HEADER_BACKUP}"

build_one iphoneos arm64 YES
build_one iphonesimulator arm64 YES
build_one iphonesimulator x86_64 YES

# The CocoaPods wrapper target is named CleanFFmpeg. The bundled static
# library must use a distinct name, otherwise -lCleanFFmpeg links that wrapper
# back to itself and leaves all FFmpeg symbols out of the final App link.
DEVICE_LIB="${DEVICE_BUILD_DIR}/install/lib/libCleanFFmpegCore.a"
SIM_ARM64_LIB="${SIM_ARM64_BUILD_DIR}/install/lib/libCleanFFmpegCore.a"
SIM_X86_64_LIB="${SIM_X86_64_BUILD_DIR}/install/lib/libCleanFFmpegCore.a"
SIM_UNIVERSAL_LIB="${SIM_UNIVERSAL_DIR}/libCleanFFmpegCore.a"
DEVICE_HEADERS="${DEVICE_BUILD_DIR}/install/include"

# The umbrella header is owned by this wrapper pod rather than FFmpeg's
# install step. Add it before packaging so <CleanFFmpeg/CleanFFmpeg.h> works
# from the generated XCFramework headers directory.
cp "${ROOT_DIR}/CleanFFmpeg.h" "${DEVICE_HEADERS}/CleanFFmpeg.h"
cp "${PREFIX_HEADER_BACKUP}" "${DEVICE_HEADERS}/cleanffmpeg_prefix.h"

mkdir -p "${DEVICE_BUILD_DIR}/install/lib" "${SIM_ARM64_BUILD_DIR}/install/lib" "${SIM_X86_64_BUILD_DIR}/install/lib" "${SIM_UNIVERSAL_DIR}"

libtool -static -o "${DEVICE_LIB}" \
  "${DEVICE_BUILD_DIR}/install/lib/libavutil.a" \
  "${DEVICE_BUILD_DIR}/install/lib/libavcodec.a" \
  "${DEVICE_BUILD_DIR}/install/lib/libavformat.a"

libtool -static -o "${SIM_ARM64_LIB}" \
  "${SIM_ARM64_BUILD_DIR}/install/lib/libavutil.a" \
  "${SIM_ARM64_BUILD_DIR}/install/lib/libavcodec.a" \
  "${SIM_ARM64_BUILD_DIR}/install/lib/libavformat.a"

libtool -static -o "${SIM_X86_64_LIB}" \
  "${SIM_X86_64_BUILD_DIR}/install/lib/libavutil.a" \
  "${SIM_X86_64_BUILD_DIR}/install/lib/libavcodec.a" \
  "${SIM_X86_64_BUILD_DIR}/install/lib/libavformat.a"

rm -f "${SIM_UNIVERSAL_LIB}"
lipo -create \
  "${SIM_ARM64_LIB}" \
  "${SIM_X86_64_LIB}" \
  -output "${SIM_UNIVERSAL_LIB}"

rm -rf "${XCFRAMEWORK_DIR}"
xcodebuild -create-xcframework \
  -library "${DEVICE_LIB}" -headers "${DEVICE_HEADERS}" \
  -library "${SIM_UNIVERSAL_LIB}" -headers "${DEVICE_HEADERS}" \
  -output "${XCFRAMEWORK_DIR}"

# Keep the wrapper header in the final public header root. This also makes
# the result resilient to xcodebuild/CocoaPods header filtering.
for slice_headers in "${XCFRAMEWORK_DIR}"/*/Headers; do
  cp "${ROOT_DIR}/CleanFFmpeg.h" "${slice_headers}/CleanFFmpeg.h"
done

copy_public_headers "${BUILD_DIR}/iphoneos/arm64/install/include"

echo "CleanFFmpeg build finished."
